-- ==============================================================================
-- UPA-GURU Database Verification: AI Extraction Schema & Draft JSONB Structure
-- File: extraction-schema-verification-v1.sql
-- Associated Task: TASK-04020101
-- Description:
--   Verifies that public.draft_notifications column definitions accept the
--   structured JSON payload generated by NotificationExtractedData.
-- ==============================================================================

-- 1. Inspect draft_notifications column types for extraction payloads
SELECT 
    column_name, 
    data_type, 
    is_nullable 
FROM information_schema.columns 
WHERE table_name = 'draft_notifications' 
  AND column_name IN (
      'parsed_json', 
      'raw_text', 
      'extraction_confidence_score', 
      'completeness_score', 
      'validation_warnings', 
      'priority_review',
      'is_corrigendum',
      'parent_draft_id'
  )
ORDER BY column_name;

-- 2. Verify GIN indexing on parsed_json for accelerated admin search
SELECT 
    schemaname, 
    tablename, 
    indexname, 
    indexdef 
FROM pg_indexes 
WHERE tablename = 'draft_notifications' 
  AND (indexdef ILIKE '%parsed_json%' OR indexname ILIKE '%parsed_json%');

-- 3. Verify sample draft payload structure validation query
SELECT 
    id, 
    parsed_json->>'title' AS extracted_title,
    parsed_json->'important_dates'->>'application_end' AS deadline,
    parsed_json->>'total_vacancies' AS vacancies,
    status,
    priority_review
FROM public.draft_notifications
LIMIT 5;
