-- ==============================================================================
-- UPA-GURU Database Verification: Scheduler & Deduplication Telemetry
-- File: scheduler-telemetry-verification-v1.sql
-- Associated Task: TASK-04010104
-- Description:
--   Verifies crawl telemetry generated by scheduled cron runs and deduplication efficiency.
-- ==============================================================================

-- 1. Review recent scheduled crawl runs with run durations
SELECT 
    id,
    portal_code,
    status,
    started_at,
    finished_at,
    EXTRACT(EPOCH FROM (finished_at - started_at)) AS duration_seconds,
    pdfs_found,
    pdfs_new,
    pdfs_failed
FROM public.crawl_runs
ORDER BY started_at DESC
LIMIT 20;

-- 2. Measure deduplication skip ratio per portal
SELECT 
    portal_code,
    COUNT(*) AS total_runs,
    SUM(pdfs_found) AS total_pdfs_detected,
    SUM(pdfs_new) AS total_new_extracted,
    CASE 
        WHEN SUM(pdfs_found) > 0 
        THEN ROUND(((SUM(pdfs_found) - SUM(pdfs_new))::numeric / SUM(pdfs_found)::numeric) * 100, 2)
        ELSE 0 
    END AS deduplication_efficiency_percent
FROM public.crawl_runs
GROUP BY portal_code;
